stages:
  - deploy

deploy:
  image: node:8
  stage: deploy
  tags: 
    - gitlab-org
  script:
    - echo "Start deploy"
    - npm install -g firebase-tools
    - yarn
    - yarn run build
    - firebase -V
    - firebase list
    - cd ./build
    - firebase use --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
  only:
    - dev