export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    EMAIL_REQUEST: 'SEND_EMAIL_REQUEST',
    EMAIL_SUCCESS: 'SEND_EMAIL_SUCCESS',
    EMAIL_FAILURE: 'SEND_EMAIL_FAILURE',

    UPDATE: 'USERS_UPDATE',

    LOGOUT: 'USERS_LOGOUT',

    SOCIAL_FB_SUCCESS: 'SOCIAL_FB_LOGIN_SUCCESS',
    SOCIAL_G_SUCCESS: 'SOCIAL_G_LOGIN_SUCCESS',
};